/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/base-ball-ball-f923538fe3034464aeeef036d2b6afe6
title: Base Ball Ball
*/

import React, { useRef, Suspense, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/baseball/scene-transformed.glb');


  return (
    <Suspense fallback={null}>
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        {/* <group rotation={[-Math.PI, 0, 0]} scale={0.03}> */}
        <group rotation={[-Math.PI, 0, 0]} scale={3}>
          <mesh
            geometry={nodes['BaseballBall-_BaseballBall_0'].geometry}
            material={materials.BaseballBall}
          />
        </group>
      </group>
    </group>
    </Suspense>
  );
}
useGLTF.preload('/baseball/scene.gltf');

// useGLTF.preload('/baseball/scene-transformed.glb');
