/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Stevenson (https://sketchfab.com/3dCoast)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tyrannosaurus-rex-20-512712b314404760a860389ebd0ce78a
title: Tyrannosaurus Rex 2.0
*/

import React, { useRef, Suspense, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Rex({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rex/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_146.geometry}
              material={materials.BodyMat}
              skeleton={nodes.Object_146.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_147.geometry}
              material={nodes.Object_147.material}
              skeleton={nodes.Object_147.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_148.geometry}
              material={nodes.Object_148.material}
              skeleton={nodes.Object_148.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_150.geometry}
              material={nodes.Object_150.material}
              skeleton={nodes.Object_150.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_151.geometry}
              material={nodes.Object_151.material}
              skeleton={nodes.Object_151.skeleton}
              onClick={(e) => actions[Object.keys(actions)[0]].play()}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rex/scene-transformed.glb')
